version: '3'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '8081:8081'
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    build: ./backend
    restart: always
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
