export const SET_CURRENT_POST = 'POST/SET_CURRENT_POST'

export const SET_SEARCH_QUERY = 'SEARCH/SET_SEARCH_QUERY'
export const SET_SEARCH_FILTERS = 'SEARCH/SET_SEARCH_FILTERS'
export const SET_SEARCH_CATEGORY = 'SEARCH/SET_SEARCH_CATEGORY'

export const TOGGLE_DARK_THEME = 'SETTINGS/TOGGLE_DARK_THEME'
export const TOGGLE_NOTIFICATIONS_ENABLED =
    'SETTINGS/TOGGLE_NOTIFICATIONS_ENABLED'
