"""Feedback model created

Revision ID: 060ff78899a2
Revises: 3fc32c873072
Create Date: 2022-02-12 12:43:30.272713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "060ff78899a2"
down_revision = "3fc32c873072"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("body", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    # ### end Alembic commands ###
