"""Removed columns

Revision ID: 49a0a5e2fd03
Revises: 2c41b5dd546a
Create Date: 2022-01-11 09:47:29.259158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a0a5e2fd03'
down_revision = '2c41b5dd546a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('boba')
        batch_op.drop_column('xui')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xui', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('boba', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
