"""123

Revision ID: 8ada534f7e12
Revises: 99367d342a8d
Create Date: 2022-06-05 13:31:52.430145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ada534f7e12"
down_revision = "99367d342a8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
