"""User and feedback relationship added

Revision ID: 99367d342a8d
Revises: 060ff78899a2
Create Date: 2022-05-14 19:39:44.513236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99367d342a8d"
down_revision = "060ff78899a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
