"""Modified task table columns

Revision ID: 3fdc8f6ad636
Revises: d8347cddf1ef
Create Date: 2021-08-07 08:51:03.707358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdc8f6ad636'
down_revision = 'd8347cddf1ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('additional_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'additional_data')
    # ### end Alembic commands ###
