// Genratl app types
export const APP_SHOW_ALERT = 'APP/SHOW_ALERT'
export const APP_HIDE_ALERT = 'APP/HIDE_ALERT'
export const APP_USER_LOGGED_IN = 'APP/USER_LOGGED_IN'
export const APP_USER_LOGGED_OUT = 'APP/USER_LOGGED_OUT'

// Login page types
export const LOGIN_CHANGE_CODE = 'LOGIN/CHANGE_CODE'
export const LOGIN_CHANGE_NAME = 'LOGIN/CHANGE_NAME'
export const LOGIN_CHANGE_PHONE = 'LOGIN/CHANGE_PHONE'
export const LOGIN_ENABLE_BUTTON = 'LOGIN/ENABLE_BUTTON'
export const LOGIN_DISABLE_BUTTON = 'LOGIN/DISABLE_BUTTON'
export const LOGIN_PHONE_SUBMITTED = 'LOGIN/PHONE_SUBMITTED'
export const LOGIN_PHONE_CONFIRMED = 'LOGIN/PHONE_CONFIRMED'

// Welcome page types
export const WLC_SET_CURRENT_CARD = 'WLC/SET_CURRENT_CARD'
export const WLC_INCR_CURRENT_INDEX = 'WLC/INCR_CURRENT_INDEX'
export const WLC_ENABLE_SHOW_ON_START = 'WLC/ENABLE_SHOW_ON_START'
export const WLC_DISABLE_SHOW_ON_START = 'WLC/DISABLE_SHOW_ON_START'
